"""Docstring for pythonium.engine.codecs."""

from .array import (
    BooleanArrayCodec,
    ByteArrayCodec,
    DoubleArrayCodec,
    FloatArrayCodec,
    IntArrayCodec,
    LongArrayCodec,
    ShortArrayCodec,
    StringArrayCodec,
    UnsignedByteArrayCodec,
    UnsignedShortArrayCodec,
    UUIDArrayCodec,
    VarIntArrayCodec,
    VarLongArrayCodec,
)
from .base import ArrayCodec, Codec, PrimitiveCodec, resolve_codec
from .custom import (
    PositionCodec,
    StringCodec,
    UUIDCodec,
    VarIntCodec,
    VarLongCodec,
)
from .primitive import (
    BooleanCodec,
    ByteCodec,
    DoubleCodec,
    FloatCodec,
    IntCodec,
    LongCodec,
    ShortCodec,
    UnsignedByteCodec,
    UnsignedShortCodec,
)

__all__ = (
    "ArrayCodec",
    "BooleanArrayCodec",
    "BooleanCodec",
    "ByteArrayCodec",
    "ByteCodec",
    "Codec",
    "DoubleArrayCodec",
    "DoubleCodec",
    "FloatArrayCodec",
    "FloatCodec",
    "IntArrayCodec",
    "IntCodec",
    "LongArrayCodec",
    "LongCodec",
    "PositionCodec",
    "PrimitiveCodec",
    "ShortArrayCodec",
    "ShortCodec",
    "StringArrayCodec",
    "StringCodec",
    "UUIDArrayCodec",
    "UUIDCodec",
    "UnsignedByteArrayCodec",
    "UnsignedByteCodec",
    "UnsignedShortArrayCodec",
    "UnsignedShortCodec",
    "VarIntArrayCodec",
    "VarIntCodec",
    "VarLongArrayCodec",
    "VarLongCodec",
    "resolve_codec",
)
